
project_id = "uvpopbenjmnkjzjdlsnw"

[api]
enabled = true

[analytics]
enabled = false

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions.text-to-speech]
verify_jwt = true
